/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentIndexRouteImport } from './routes/equipment.index'
import { Route as EquipmentCategoryIndexRouteImport } from './routes/equipment.$category.index'
import { Route as EquipmentCategoryIdRouteImport } from './routes/equipment.$category.$id'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentCategoryIndexRoute = EquipmentCategoryIndexRouteImport.update({
  id: '/equipment/$category/',
  path: '/equipment/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentCategoryIdRoute = EquipmentCategoryIdRouteImport.update({
  id: '/equipment/$category/$id',
  path: '/equipment/$category/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/equipment/$category/$id': typeof EquipmentCategoryIdRoute
  '/equipment/$category/': typeof EquipmentCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/equipment': typeof EquipmentIndexRoute
  '/equipment/$category/$id': typeof EquipmentCategoryIdRoute
  '/equipment/$category': typeof EquipmentCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/equipment/$category/$id': typeof EquipmentCategoryIdRoute
  '/equipment/$category/': typeof EquipmentCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/equipment/'
    | '/equipment/$category/$id'
    | '/equipment/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/equipment'
    | '/equipment/$category/$id'
    | '/equipment/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/equipment/'
    | '/equipment/$category/$id'
    | '/equipment/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
  EquipmentCategoryIdRoute: typeof EquipmentCategoryIdRoute
  EquipmentCategoryIndexRoute: typeof EquipmentCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$category/': {
      id: '/equipment/$category/'
      path: '/equipment/$category'
      fullPath: '/equipment/$category/'
      preLoaderRoute: typeof EquipmentCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$category/$id': {
      id: '/equipment/$category/$id'
      path: '/equipment/$category/$id'
      fullPath: '/equipment/$category/$id'
      preLoaderRoute: typeof EquipmentCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
  EquipmentCategoryIdRoute: EquipmentCategoryIdRoute,
  EquipmentCategoryIndexRoute: EquipmentCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
